### ISSUE TITLE
Missing request forgery token when calling Insurance

### ISSUE THREAD

**Issue by emilpriverrc** [wayke-se/wayke-ecom-js#12]
Hello,
currently using your package to create a payment flow and i get "Missing request forgery token" when trying to get all insurances for a car. Have been checking the description you have but also looking at the file and didn't see anything that could help me.

the code:
```
const request = insurances.newInsuranceOptionsRequest()
        .forCustomer('X')
        .forVehicle('CAR ID)
        .withPaymentType('Loan')
        .withDrivingDistance('Between1000And1500')
        .build()

      const response = await insurances.getOptions(request)
```

Do you know what I am doing wrong

**Comment by ourbjorn** [comment]
Hi @emilpriverrc , sorry for the late response!

Before any other request, an "initialization request" has to happen - via:
```
const request = orders.newOptionsRequest()
    .forVehicle("VEHICLE-ID-FROM-WAYKE")
    .build();

try {
    const response = await orders.getOptions(request);
} catch (e) {
    console.error(e)
}
```

This initial request correctly stores a request forgery token, which is used in later requests.

**Comment by emilpriverrc** [comment]
Hi :D @ourbjorn.
No probbs, Your support helped me and we have a working buy flow atm :D 

Thank you for your response :D
